name: Prebuild

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2

jobs:
  prebuild:
    name: Prebuild
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-22.04, windows-2022, macos-14]

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Prebuild
        run: |
          pnpm cmake-js build
          pnpm pkg-prebuilds-copy --baseDir build/Release --source pcre2.node --name=pcre2 --strip --napi_version=8

      - name: Prebuild (x64)
        if: startsWith(matrix.runs-on, 'macos')
        run: |
          pnpm cmake-js build --arch x64
          pnpm pkg-prebuilds-copy --baseDir build/Release --source pcre2.node --name=pcre2 --strip --napi_version=8 --arch x64

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: prebuilds-${{ matrix.runs-on }}
          path: prebuilds
